
trigger:
- main
- dev
- dev-gui
- feature/*
- hotfix/*
- release/*

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install build
    pip install wheel
  displayName: 'Install build dependencies'

- script: |
    python setup.py sdist
  displayName: 'Build Yawning-Titan'

- script: |
    YT=$(ls ./dist/yawningtitan-*.*.*.tar.gz)
    python -m pip install torch==1.11+cpu -f https://download.pytorch.org/whl/torch_stable.html
    python -m pip install $YT[dev] --default-timeout 1000
  displayName: 'Install Yawning-Titan'

- script: |
    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  displayName: 'Lint with flake8'

- script: |
    pip install pytest-azurepipelines
    pytest tests
  displayName: 'Test with pytest'
